name: Thomas Radman
favicon: null
layout_spectrum: 0.81577
typography_spectrum: 0.92243
title: this is not the end
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7894aa'
    - '#0a0a0c'
    - '#896b45'
    - '#fefee4'
    - '#82b414'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
