name: Thomas Radman
favicon: null
layout_spectrum: 0.25498
typography_spectrum: 0.4334
title: this is not the end
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#292b2c'
    - '#f49b73'
    - '#666663'
    - '#778ebd'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
